DROP VIEW viewrollos;

CREATE 
VIEW `viewrollos` AS
    SELECT 
        `r`.`idRollo` AS `idRollo`,
        `r`.`codigo` AS `codigo`,
        `rm`.`idMaterial` AS `idMaterial`,
        `rm`.`nombre` AS `material`,
        `rm`.`clave` AS `shortMaterial`,
        `rp`.`idProveedor` AS `idProveedor`,
        `rp`.`nombre` AS `proveedor`,
        `rp`.`clave` AS `shortProveedor`,
        `col`.`idColor` AS `idColor`,
        `col`.`nombre` AS `color`,
        `col`.`clave` AS `shortColor`,
        `r`.`calibre` AS `calibre`,
        `r`.`pies` AS `pies`,
        IF((`r`.`pies` = 2),
            `pesomt`.`pies2`,
            IF((`r`.`pies` = 3),
                `pesomt`.`pies3`,
                IF((`r`.`pies` = 3.48),
                    `pesomt`.`pies348`,
                    IF((`r`.`pies` = 3.76),
                        `pesomt`.`pies376`,
                        IF((`r`.`pies` = 4),
                            `pesomt`.`pies4`,
                            0))))) AS `pesokiloml`,
        `r`.`origen` AS `origen`,
        `r`.`grado` AS `grado`,
        `r`.`existencia` AS `existencia`,
        `r`.`apartado` AS `apartado`,
        `r`.`descripcion` AS `descripcion`,
        IF((`r`.`idRollo` > 1),
            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('ROLLO ',
                                        `rm`.`nombre`,
                                        ' CAL ',
                                        `r`.`calibre`,
                                        ' ',
                                        `r`.`pies`,
                                        ' PIES ',
                                        IF((`r`.`origen` = 'I'),
                                            ' IMPORTADO ',
                                            ' NACIONAL '),
                                        `rp`.`nombre`,
                                        IF((`r`.`grado` > 0),
                                            CONCAT(' GRADO ', `r`.`grado`),
                                            ''),
                                        IF((`r`.`rollo_color_idColor` > 1),
                                            CONCAT(' ', `col`.`nombre`),
                                            '')),
                                '-- NO APLICA --',
                                ''),
                            '--NO APLICA--',
                            ''),
                        'CAL 0',
                        ''),
                    '0 PIES',
                    ''),
                '  ',
                ' '),
            '-- NO APLICA --') AS `descauto`,
        `r`.`observaciones` AS `observaciones`,
        `r`.`estado` AS `estado`,
        `r`.`iva` AS `iva`,
        `r`.`prodmes` AS `prodmes`,
        `r`.`porutilidad` AS `porutilidad`,
        `r`.`porcomision` AS `porcomision`,
        `r`.`descuento` AS `descuento`,
        `r`.`costoflete` AS `costoflete`,
        `r`.`costokg` AS `costokg`,
        `r`.`pesokgmt` AS `pesokgmt`,
        `r`.`pesocu` AS `pesocu`,
        `r`.`pesoimporte` AS `pesoimporte`,
        `r`.`pesoparti` AS `pesoparti`,
        `r`.`fmod` AS `fmod`,
        `r`.`moi` AS `moi`,
        `r`.`gastosfab` AS `gastosfab`,
        `r`.`comisiones` AS `comisiones`,
        `r`.`gastosventa` AS `gastosventa`,
        `r`.`gastosfinancieros` AS `gastosfinancieros`,
        `r`.`gastosadmon` AS `gastosadmon`,
        `r`.`modiva` AS `modiva`,
        `r`.`moiiva` AS `moiiva`,
        `r`.`gastosfabiva` AS `gastosfabiva`,
        `r`.`comisionesiva` AS `comisionesiva`,
        `r`.`gastosventaiva` AS `gastosventaiva`,
        `r`.`gastosfinancierosiva` AS `gastosfinancierosiva`,
        `r`.`gastosadmoniva` AS `gastosadmoniva`,
        `r`.`modparti` AS `modparti`,
        `r`.`moiparti` AS `moiparti`,
        `r`.`gastosfabparti` AS `gastosfabparti`,
        `r`.`comisionesparti` AS `comisionesparti`,
        `r`.`gastosventaparti` AS `gastosventaparti`,
        `r`.`gastosfinancierosparti` AS `gastosfinancierosparti`,
        `r`.`gastosadmonparti` AS `gastosadmonparti`,
        `r`.`totalessummes` AS `totalessumames`,
        `r`.`totalessumkg` AS `totalessumkg`,
        `r`.`totalespeso` AS `totalespeso`,
        `r`.`totalesfab` AS `totalesfab`,
        `r`.`totalcostofab` AS `totalcostofab`,
        `r`.`totalpreciovta` AS `totalpreciovta`,
        `r`.`totalpreciovtar2` AS `totalpreciovtar2`,
        `r`.`totalpreciovtar3` AS `totalpreciovtar3`,
        `r`.`totalpreciovtar4` AS `totalpreciovtar4`
    FROM
        ((((`rollo` `r`
        JOIN `material` `rm` ON ((`rm`.`idMaterial` = `r`.`rollo_material_idMaterial`)))
        JOIN `color` `col` ON ((`col`.`idColor` = `r`.`rollo_color_idColor`)))
        JOIN `proveedor` `rp` ON ((`rp`.`idProveedor` = `r`.`rollo_proveedor_idProveedor`)))
        LEFT JOIN `pesomt` ON ((`pesomt`.`calibre` = `r`.`calibre`)))
		
		
		
		
		
		