DROP VIEW viewproductos;

CREATE 
VIEW `viewproductos` AS
    SELECT 
        `p`.`idProducto` AS `idProducto`,
        `p`.`codigo` AS `codigo`,
        `p`.`longitud` AS `longitud`,
        `p`.`mlpieza` AS `mlpieza`,
		`p`.`medidaespecial` AS `medidaespecial`,		
        `tp`.`idTipoProducto` AS `idTipoProducto`,
        `tp`.`nombre` AS `tipoProducto`,
        `tp`.`clave` AS `shortTipoProducto`,
		`col`.`idColor` AS `idColor`,
		`col`.`nombre` AS `color`,
        `a`.`idAplicacion` AS `idAplicacion`,
        `a`.`nombreAplicacion` AS `aplicacion`,
        `m`.`idMaterial` AS `idMaterial`,
		`m`.`clave` AS `claveMaterial`,
        `m`.`nombre` AS `material`,
        `r`.`idRollo` AS `idRollo`,
        `r`.`codigo` AS `rolloCodigo`,
        `r`.`descauto` AS `rollodescauto`,
        `rm`.`idMaterial` AS `rolloIdMaterial`,
        `rm`.`nombre` AS `rolloMaterial`,
        `rm`.`clave` AS `rolloShortMaterial`,
        `rp`.`idProveedor` AS `rolloIdProveedor`,
        `rp`.`nombre` AS `rolloProveedor`,
        IF (`p`.`medidaespecial` = '' , 
				`rp`.`nombre`,
				IF (`m`.`nombre` LIKE '%ISO%' , 
					'ISOCINDU',
					'TERNIUM')) proveedorcalc,
        `rp`.`clave` AS `rolloShortProveedor`,
        `r`.`calibre` AS `rolloCalibre`,
        `r`.`pies` AS `rolloPies`,
        `r`.`pesokiloml` AS `rolloPesokiloml`,
        `r`.`origen` AS `rolloOrigen`,
        `r`.`existencia` AS `rolloExistencia`,
        `r`.`apartado` AS `rolloApartado`,
        `r`.`descripcion` AS `rolloDescripcion`,
        `r`.`iva` AS `rolloIva`,
        `r`.`prodmes` AS `rolloProdmes`,
        `r`.`porutilidad` AS `rolloPorutilidad`,
        `r`.`porcomision` AS `rolloPorcomision`,
        `r`.`descuento` AS `rolloDescuento`,
        `r`.`costoflete` AS `rolloCostoflete`,
        `r`.`costokg` AS `rolloCostokg`,
        `r`.`pesokgmt` AS `rolloPesokgmt`,
        `r`.`pesocu` AS `rolloPesocu`,
        `r`.`pesoimporte` AS `rolloPesoimporte`,
        `r`.`pesoparti` AS `rolloPesoparti`,
        `r`.`fmod` AS `rolloFmod`,
        `r`.`moi` AS `rolloMoi`,
        `r`.`gastosfab` AS `rolloGastosfab`,
        `r`.`comisiones` AS `rolloComisiones`,
        `r`.`gastosventa` AS `rolloGastosventa`,
        `r`.`gastosfinancieros` AS `rolloGastosfinancieros`,
        `r`.`gastosadmon` AS `rolloGastosadmon`,
        `r`.`modiva` AS `rolloModiva`,
        `r`.`moiiva` AS `rolloMoiiva`,
        `r`.`gastosfabiva` AS `rolloGastosfabiva`,
        `r`.`comisionesiva` AS `rolloComisionesiva`,
        `r`.`gastosventaiva` AS `rolloGastosventaiva`,
        `r`.`gastosfinancierosiva` AS `rolloGastosfinancierosiva`,
        `r`.`gastosadmoniva` AS `rolloGastosadmoniva`,
        `r`.`modparti` AS `rolloModparti`,
        `r`.`moiparti` AS `rolloMoiparti`,
        `r`.`gastosfabparti` AS `rolloGastosfabparti`,
        `r`.`comisionesparti` AS `rolloComisionesparti`,
        `r`.`gastosventaparti` AS `rolloGastosventaparti`,
        `r`.`gastosfinancierosparti` AS `rolloGastosfinancierosparti`,
        `r`.`gastosadmonparti` AS `rolloGastosadmonparti`,
        `r`.`totalessumames` AS `rolloTotalessumames`,
        `r`.`totalessumkg` AS `rolloTotalessumkg`,
        `r`.`totalespeso` AS `rolloTotalespeso`,
        `r`.`totalesfab` AS `rolloTotalesfab`,
        `r`.`totalcostofab` AS `rolloTotalcostofab`,
        `r`.`totalpreciovta` AS `rolloTotalpreciovta`,
        `r`.`totalpreciovtar2` AS `rolloTotalpreciovtar2`,
        `r`.`totalpreciovtar3` AS `rolloTotalpreciovtar3`,
        `r`.`totalpreciovtar4` AS `rolloTotalpreciovtar4`,
        `u`.`idUnidad` AS `idUnidad`,
		IF(((`m`.`idMaterial` = 29)
                                                        OR (`m`.`idMaterial` = 17)
                                                        OR (`m`.`idMaterial` = 28)
                                                        OR (`m`.`idMaterial` = 31)
                                                        OR (`m`.`idMaterial` = 30)
                                                        OR (`m`.`idMaterial` = 11)
                                                        OR (`m`.`idMaterial` = 35)
                                                        OR (`m`.`idMaterial` = 36)
                                                        OR (`m`.`idMaterial` = 37)
                                                        OR (`m`.`idMaterial` = 38)),
                                                    'PULGADAS',
                                                    IF(((`r`.`pies` > 0.0) OR (`p`.`pies` > 0.0)),
                                                        'PIES',
                                                        'NA')) unidadCalc,
        `u`.`descripcion` AS `unidad`,
        `u`.`clave` AS `shortUnidad`,
        `p`.`calibre` AS `calibre`,
        `p`.`pies` AS `pies`,
        `p`.`descripcion` AS `descripcion`,
        `p`.`existencia` AS `existencia`,
        `p`.`apartado` AS `apartado`,
        `p`.`apartadoReal` AS `apartadoReal`,
        `p`.`tipoPrecio` AS `tipoPrecio`,
        `p`.`isRango` AS `isRango`,
        `p`.`tipoRango` AS `tipoRango`,
        `p`.`isRollo` AS `isRollo`,
        `p`.`heredarPrecio` AS `heredarPrecio`,
        `p`.`costo` AS `costo`,
        `p`.`precio1` AS `precio1`,
        `p`.`precio2` AS `precio2`,
        `p`.`precio3` AS `precio3`,
        `p`.`precio4` AS `precio4`,
        IF((`p`.`preciomendez` > 0),
            `p`.`preciomendez`,
            IF((`p`.`precio3` > 0),
                `p`.`precio3`,
                IF((`p`.`precio2` > 0),
                    `p`.`precio2`,
                    `p`.`precio1`))) AS `preciomendez`,
        `p`.`estado` AS `estado`,
        REPLACE(IF((`tp`.`idTipoProducto` = 4),
                `p`.`descripcion`,
                REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT(`tp`.`nombre`,
                                                ' ',
                                                IF((`a`.`nombreAplicacion` LIKE '%PYC%'),
                                                    ' PUNTAS Y COLAS ',
                                                    ''),
                                                `a`.`nombreAplicacion`,
                                                ' ',
                                                `m`.`nombre`,
                                                IF((`m`.`idMaterial` = 15), '  ', ' '),
                                                IF((`r`.`calibre` > 0),
                                                    CONCAT('CAL ', `r`.`calibre`, ' '),
                                                    IF((`p`.`calibre` > 0),
                                                        CONCAT(' CAL ', `p`.`calibre`, ' '),
                                                        '')),
                                                ' ',
                                                IF((`m`.`idMaterial` = 15),
                                                    ' OZ ',
                                                    '  '),
                                                IF((`p`.`medidaespecial` <> ''),
                                                    CONCAT(' ', `p`.`medidaespecial`,IF(`p`.`producto_material_idMaterial` IN (62, 63) ,'MM','') ),
                                                    ''),
                                                IF((`r`.`pies` > 0.0),
                                                    `r`.`pies`,
                                                    IF((`p`.`pies` > 0.0), `p`.`pies`, '')),
                                                IF(((`m`.`idMaterial` = 29)
                                                        OR (`m`.`idMaterial` = 17)
                                                        OR (`m`.`idMaterial` = 28)
                                                        OR (`m`.`idMaterial` = 31)
                                                        OR (`m`.`idMaterial` = 30)
                                                        OR (`m`.`idMaterial` = 11)
                                                        OR (`m`.`idMaterial` = 35)
                                                        OR (`m`.`idMaterial` = 36)
                                                        OR (`m`.`idMaterial` = 37)
                                                        OR (`m`.`idMaterial` = 38)),
                                                    ' PULGADAS',
                                                    IF(((`r`.`pies` > 0.0) OR (`p`.`pies` > 0.0)),
                                                        ' PIES ',
                                                        '')),
                                                IF((`r`.`idRollo` > 1),
                                                    IF((`p`.`origen` = 1),
                                                        ' NACIONAL ',
                                                        ' IMPORTADO '),
                                                    ''),
                                                `rp`.`nombre`,
                                                ' ',
                                                IF(((`r`.`grado` > 0)
                                                        AND (`r`.`idRollo` > 0)),
                                                    CONCAT(' GRADO ', `r`.`grado`, ' '),
                                                    ''),
                                                IF((`r`.`idColor` > 1),
                                                    CONCAT(' ', `col`.`nombre`),
                                                    ''),
                                                `p`.`longitud`,
                                                IF((`p`.`longitud` LIKE '%X%'),
                                                    '',
                                                    IF((`p`.`longitud` <> ''),
                                                        IF(`p`.`producto_material_idMaterial` IN (62, 63)  ,' ML',' MTS') , '')),
                                                IF((`r`.`idRollo` = 1),
                                                    IF((`p`.`origen` = 1),
                                                        ' NACIONAL',
                                                        IF(`p`.`producto_material_idMaterial` IN (62, 63) ,' ','IMPORTADO')),
                                                    '')),
                                        '-- NO APLICA --',
                                        ''),
                                    '--NO APLICA--',
                                    ''),
                                'CAL 0.00',
                                ''),
                            '0.00 PIES',
                            ''),
                        '  ',
                        ' '),
                    '0.00 PULGADAS',
                    '')),
            '  ',
            ' ') AS `descauto`
    FROM
        ((((((((`producto` `p`
        JOIN `tipoproducto` `tp` ON ((`tp`.`idTipoProducto` = `p`.`producto_tipoProducto_idTipoProducto`)))
        JOIN `aplicacion` `a` ON ((`a`.`idAplicacion` = `p`.`producto_aplicacion_idAplicacion`)))
        JOIN `material` `m` ON ((`m`.`idMaterial` = `p`.`producto_material_idMaterial`)))
        JOIN `viewrollos` `r` ON ((`r`.`idRollo` = `p`.`producto_rollo_idRollo`)))
        JOIN `color` `col` ON ((`col`.`idColor` = `r`.`idColor`)))
        JOIN `unidad` `u` ON ((`u`.`idUnidad` = `p`.`producto_unidad_idUnidad`)))
        JOIN `material` `rm` ON ((`rm`.`idMaterial` = `r`.`idMaterial`)))
        JOIN `proveedor` `rp` ON ((`rp`.`idProveedor` = `r`.`idProveedor`)))